# Translations template for keystone.
# Copyright (C) 2015 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
# Zhong Chaoliang <charliezon@gmail.com>, 2013
# Dongliang Yu <yudl.nju@gmail.com>, 2013
# Lee Yao <yaoli111144@gmail.com>, 2013
# Lee Yao <yaoli111144@gmail.com>, 2013
# Zhong Chaoliang <charliezon@gmail.com>, 2013
# 颜海峰 <yanheven@gmail.com>, 2014
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
# Eric Lei <1165970798@qq.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: keystone 10.0.0.0rc2.dev181\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-21 07:06+0000\n"
"PO-Revision-Date: 2019-04-12 13:18+0000\n"
"Last-Translator: Eric Lei <Unknown>\n"
"Language-Team: Chinese (China)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2019-05-11 13:06+0000\n"
"X-Generator: Launchpad (build 18962)\n"
"Language: zh-CN\n"
"Generated-By: Babel 2.0\n"

#: keystone/exception.py:83
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not comply "
"with the request since it is either malformed or otherwise incorrect. The "
"client is assumed to be in error."
msgstr ""
"期望在 %(target)s 中找到 %(attribute)s - 服务器未能遵照请求，因为它的格式或者其他方面不正确。客户机被认为发生错误。"

#: keystone/exception.py:92
#, python-format
msgid "Cannot create an endpoint with an invalid URL: %(url)s"
msgstr "无法创建具有无效 URL %(url)s 的端点"

#: keystone/exception.py:99
#, python-format
msgid "%(detail)s"
msgstr "%(detail)s"

#: keystone/exception.py:103
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client is "
"assumed to be in error."
msgstr "时间戳记未采用所需格式。服务器未能遵照请求，因为它的格式或者其他方面不正确。客户机被认为发生错误。"

#: keystone/exception.py:112
msgid ""
"The 'expires_at' must not be before now. The server could not comply with "
"the request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr "“expires_at”不得早于现在。服务器未能遵从请求，因为它的格式不正确，或者其他方面不正确。客户机被认为发生错误。"

#: keystone/exception.py:121
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the limit "
"of column %(type)s(CHAR(%(length)d))."
msgstr "字符串长度过长。字符串“%(string)s”的长度超过列限制 %(type)s（字符(%(length)d)）。"

#: keystone/exception.py:127
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. The "
"server could not comply with the request because the attribute size is "
"invalid (too large). The client is assumed to be in error."
msgstr ""
"请求属性 %(attribute)s 必须小于或等于 %(size)i。服务器未能遵照请求，因为属性大小无效（太大）。客户机被认为发生错误。"

#: keystone/exception.py:137
#, python-format
msgid ""
"The specified parent region %(parent_region_id)s would create a circular "
"region hierarchy."
msgstr "指定的父区域 %(parent_region_id)s 将创建循环区域层次结构。"

#: keystone/exception.py:156
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server could "
"not comply with the request because the password is invalid."
msgstr "密码长度必须小于或等于 %(size)i。服务器未能遵照请求，因为密码无效。"

#: keystone/exception.py:162
#, python-format
msgid ""
"Unable to delete region %(region_id)s because it or its child regions have "
"associated endpoints."
msgstr "无法删除区域 %(region_id)s，因为它或它的子区域具有关联的端点。"

#: keystone/exception.py:167
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr "请求的证书不可用。可能此服务器未使用 PKI 令牌，或者这是因为配置错误。"

#: keystone/exception.py:179
msgid "(Disable insecure_debug mode to suppress these details.)"
msgstr "（禁用 insecure_debug 方式以避免显示这些详细信息。）"

#: keystone/exception.py:189
#, python-format
msgid "%(message)s %(amendment)s"
msgstr "%(message)s %(amendment)s"

#: keystone/exception.py:197
msgid "The request you have made requires authentication."
msgstr "你的请求需要先授权"

#: keystone/exception.py:203
msgid "Authentication plugin error."
msgstr "认证插件错误"

#: keystone/exception.py:211
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr "使用映射 %(mapping_id)s 时，找不到有效组"

#: keystone/exception.py:216
msgid "Attempted to authenticate with an unsupported method."
msgstr "尝试使用未支持的方法进行验证"

#: keystone/exception.py:224
msgid "Additional authentications steps required."
msgstr "需要额外身份验证"

#: keystone/exception.py:232
msgid "You are not authorized to perform the requested action."
msgstr "您没有授权完成所请求的操作。"

#: keystone/exception.py:239
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr "您无权执行请求的操作：%(action)s"

#: keystone/exception.py:244
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target %(target)s"
msgstr "无法更改目标 %(target)s 中的不可变属性 %(attributes)s"

#: keystone/exception.py:249
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in question "
"is %(group_id)s, user is %(user_id)s"
msgstr "不允许使用跨后端边界的组成员资格，所提到的组为%(group_id)s，用户为 %(user_id)s"

#: keystone/exception.py:255
#, python-format
msgid ""
"Invalid mix of entities for policy association - only Endpoint, Service or "
"Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, Service: "
"%(service_id)s, Region: %(region_id)s"
msgstr ""
"用于策略关联的实体混合无效 - 仅允许“端点”、“服务”或“区域 + 服务”。请求为 - "
"端点：%(endpoint_id)s，服务：%(service_id)s，区域：%(region_id)s"

#: keystone/exception.py:262
#, python-format
msgid "Invalid domain specific configuration: %(reason)s"
msgstr "特定于域的配置无效：%(reason)s"

#: keystone/exception.py:266
#, python-format
msgid "Could not find: %(target)s"
msgstr "找不到 %(target)s"

#: keystone/exception.py:272
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr "找不到端点：%(endpoint_id)s"

#: keystone/exception.py:279
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr "发送了无法处理的异常：找不到元数据。"

#: keystone/exception.py:284
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr "找不到策略：%(policy_id)s"

#: keystone/exception.py:288
msgid "Could not find policy association"
msgstr "找不到策略关联"

#: keystone/exception.py:292
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr "找不到角色：%(role_id)s"

#: keystone/exception.py:296
#, python-format
msgid "%(prior_role_id)s does not imply %(implied_role_id)s"
msgstr "%(prior_role_id)s 并未暗示 %(implied_role_id)s"

#: keystone/exception.py:300
#, python-format
msgid "%(role_id)s cannot be an implied roles"
msgstr "%(role_id)s 不能是暗示角色"

#: keystone/exception.py:304
#, python-format
msgid ""
"Could not find role assignment with role: %(role_id)s, user or group: "
"%(actor_id)s, project or domain: %(target_id)s"
msgstr "找不到角色分配，角色为 %(role_id)s，用户或组为 %(actor_id)s，项目或域为 %(target_id)s"

#: keystone/exception.py:310
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr "找不到区域：%(region_id)s"

#: keystone/exception.py:314
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr "找不到服务：%(service_id)s"

#: keystone/exception.py:318
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr "找不到域：%(domain_id)s"

#: keystone/exception.py:322
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr "找不到项目：%(project_id)s"

#: keystone/exception.py:326
#, python-format
msgid "Cannot create project with parent: %(project_id)s"
msgstr "无法创建具有父代的项目：%(project_id)s"

#: keystone/exception.py:330
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr "找不到令牌：%(token_id)s"

#: keystone/exception.py:334
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr "找不到用户：%(user_id)s"

#: keystone/exception.py:338
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr "找不到组：%(group_id)s"

#: keystone/exception.py:342
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr "找不到映射：%(mapping_id)s"

#: keystone/exception.py:346
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr "找不到信任：%(trust_id)s"

#: keystone/exception.py:350
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr "对于信任 %(trust_id)s，不存在其余使用"

#: keystone/exception.py:354
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr "找不到凭证：%(credential_id)s"

#: keystone/exception.py:358
#, python-format
msgid "Could not find version: %(version)s"
msgstr "找不到版本：%(version)s"

#: keystone/exception.py:362
#, python-format
msgid "Could not find Endpoint Group: %(endpoint_group_id)s"
msgstr "找不到端点组：%(endpoint_group_id)s"

#: keystone/exception.py:366
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr "找不到身份提供者：%(idp_id)s"

#: keystone/exception.py:370
#, python-format
msgid "Could not find Service Provider: %(sp_id)s"
msgstr "找不到服务提供程序：%(sp_id)s"

#: keystone/exception.py:374
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr "找不到身份提供者 %(idp_id)s 的联合协议 %(protocol_id)s"

#: keystone/exception.py:385
#, python-format
msgid ""
"Could not find %(group_or_option)s in domain configuration for domain "
"%(domain_id)s"
msgstr "在以下域的域配置中找不到 %(group_or_option)s：%(domain_id)s"

#: keystone/exception.py:403
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr "尝试存储 %(type)s 时发生冲突 - %(details)s"

#: keystone/exception.py:412
msgid ""
"An unexpected error prevented the server from fulfilling your request."
msgstr "意外错误阻止了服务器完成您的请求。"

#: keystone/exception.py:415
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr "意外错误阻止了服务器完成您的请求：%(exception)s"

#: keystone/exception.py:433
#, python-format
msgid "Unable to consume trust %(trust_id)s, unable to acquire lock."
msgstr "无法使用信任 %(trust_id)s，无法获取锁定。"

#: keystone/exception.py:438
msgid ""
"Expected signing certificates are not available on the server. Please check "
"Keystone configuration."
msgstr "在服务器上，期望的签名证书不可用。请检查 Keystone 配置。"

#: keystone/exception.py:444
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr "不正确的端点URL(%(endpoint)s), 查看错误日志获取详情"

#: keystone/exception.py:449
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in the "
"backend."
msgstr "在后端中，找不到由映射 %(mapping_id)s 返回的组 %(group_id)s。"

#: keystone/exception.py:454
#, python-format
msgid "Error while reading metadata file, %(reason)s"
msgstr "读取元数据文件时出错，原因为 %(reason)s"

#: keystone/exception.py:458
#, python-format
msgid ""
"Local section in mapping %(mapping_id)s refers to a remote match that "
"doesn't exist (e.g. {0} in a local section)."
msgstr "映射 %(mapping_id)s 中的本地节引用不存在的远程匹配（例如，本地节中的 '{0}'）。"

#: keystone/exception.py:464
#, python-format
msgid ""
"Unexpected combination of grant attributes - User: %(user_id)s, Group: "
"%(group_id)s, Project: %(project_id)s, Domain: %(domain_id)s"
msgstr ""
"存在以下 grant 属性的意外组合 - 用户 %(user_id)s、组 %(group_id)s、项目 %(project_id)s 和域 "
"%(domain_id)s"

#: keystone/exception.py:471
msgid "The action you have requested has not been implemented."
msgstr "您请求的操作暂未被执行"

#: keystone/exception.py:478
msgid "The service you have requested is no longer available on this server."
msgstr "在此服务器上，已请求的服务不再可用。"

#: keystone/exception.py:485
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr "找不到 Keystone 配置文件 %(config_file)s。"

#: keystone/exception.py:490
msgid ""
"No encryption keys found; run keystone-manage fernet_setup to bootstrap one."
msgstr "找不到任何加密密钥；请针对引导程序 1 运行 keystone-manage fernet_setup。"

#: keystone/exception.py:495
#, python-format
msgid ""
"The Keystone domain-specific configuration has specified more than one SQL "
"driver (only one is permitted): %(source)s."
msgstr "特定于 Keystone 域的配置已指定多个 SQL 驱动程序（仅允许指定一个）：%(source)s。"

#: keystone/exception.py:502
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration repository "
"path at %(path)s doesn't exist or isn't a directory."
msgstr "%(mod_name)s 未提供数据库迁移。%(path)s 处的迁移存储库路径不存在或者不是目录。"

#: keystone/exception.py:509
msgid "Token version is unrecognizable or unsupported."
msgstr "令牌版本不可识别或者不受支持。"

#: keystone/exception.py:514
#, python-format
msgid ""
"Unable to sign SAML assertion. It is likely that this server does not have "
"xmlsec1 installed, or this is the result of misconfiguration. Reason "
"%(reason)s"
msgstr "无法对 SAML 断言进行签名。此服务器可能未安装 xmlsec1，或者这可能是由于配置错误导致的。原因 %(reason)s"

#: keystone/exception.py:521
msgid ""
"No Authorization headers found, cannot proceed with OAuth related calls, if "
"running under HTTPd or Apache, ensure WSGIPassAuthorization is set to On."
msgstr ""
"找不到任何授权头，无法继续进行与 OAuth 相关的调用，如果是通过 HTTP 或 Apache 运行，请确保 "
"WSGIPassAuthorization 设置为开启。"

#: keystone/exception.py:528
#, python-format
msgid ""
"Could not determine Identity Provider ID. The configuration option "
"%(issuer_attribute)s was not found in the request environment."
msgstr "未能确定身份提供者标识。在请求环境中找不到配置选项 %(issuer_attribute)s。"

#: keystone/exception.py:536
#, python-format
msgid ""
"The %s extension has been moved into keystone core and as such its "
"migrations are maintained by the main keystone database control. Use the "
"command: keystone-manage db_sync"
msgstr ""
"%s 扩展已移至 keystone 核心，因此，其迁移由主 keystone 数据库控件维护。使用以下命令：keystone-manage db_sync"

#: keystone/exception.py:544
#, python-format
msgid "%(driver)s is not supported driver version"
msgstr "%(driver)s 不是受支持的驱动程序版本"

#: keystone/notifications.py:232
#, python-format
msgid ""
"%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr "%(event)s 不是有效通知事件，必须是下列其中一项：%(actions)s"

#: keystone/notifications.py:241
#, python-format
msgid "Method not callable: %s"
msgstr "方法不可调用：%s"

#: keystone/assignment/controllers.py:100 keystone/identity/controllers.py:71
#: keystone/resource/controllers.py:90
msgid "Name field is required and cannot be empty"
msgstr "名称字段是必填字段，不能为空"

#: keystone/assignment/controllers.py:146
#: keystone/assignment/controllers.py:163
#: keystone/assignment/controllers.py:182
msgid "User roles not supported: tenant_id required"
msgstr "用户角色不受支持：需要 tenant_id"

#: keystone/assignment/controllers.py:567
#: keystone/assignment/controllers.py:856
msgid "Specify a domain or project, not both"
msgstr "请指定域或项目，但不是同时指定这两者"

#: keystone/assignment/controllers.py:570
msgid "Specify one of domain or project"
msgstr "请指定域或项目"

#: keystone/assignment/controllers.py:575
#: keystone/assignment/controllers.py:861
msgid "Specify a user or group, not both"
msgstr "请指定用户或组，但不是同时指定这两者"

#: keystone/assignment/controllers.py:578
msgid "Specify one of user or group"
msgstr "请指定用户或组"

#: keystone/assignment/controllers.py:845
msgid ""
"Combining effective and group filter will always result in an empty list."
msgstr "将有效过滤器与组过滤器进行组合将始终产生空列表。"

#: keystone/assignment/controllers.py:850
msgid ""
"Combining effective, domain and inherited filters will always result in an "
"empty list."
msgstr "将有效过滤器、域过滤器和继承的过滤器进行组合将始终产生空列表。"

#: keystone/assignment/controllers.py:952
msgid ""
"scope.project.id must be specified if include_subtree is also specified"
msgstr "如果还指定了 include_subtree，那么必须指定 scope.project.id"

#: keystone/assignment/core.py:77
msgid ""
"Use of the identity driver config to automatically configure the same "
"assignment driver has been deprecated, in the \"O\" release, the assignment "
"driver will need to be expicitly configured if different than the default "
"(SQL)."
msgstr "已不推荐使用标识驱动程序配置来自动配置同一分配驱动程序，在“O”发行版中，如果不同于缺省值 (SQL)，那么需要显式配置分配驱动程序。"

#: keystone/assignment/core.py:88
#, python-format
msgid ""
"Attempted automatic driver selection for assignment based upon [identity]\\"
"driver option failed since driver %s is not found. Set [assignment]/driver "
"to a valid driver in keystone config."
msgstr ""
"尝试根据 [identity]\\driver 选项为分配自动选择驱动程序失败，因为找不到驱动程序 %s。请在 keystone 配置中将 "
"[assignment]/driver 设置为有效驱动程序。"

#: keystone/assignment/core.py:179
msgid "Must specify either domain or project"
msgstr "必须指定 domain 或 project"

#: keystone/assignment/core.py:848
msgid "Cannot list assignments sourced from groups and filtered by user ID."
msgstr "无法列示源自若干组并按用户标识过滤的分配。"

#: keystone/assignment/core.py:1058
#, python-format
msgid "Project (%s)"
msgstr "项目 (%s)"

#: keystone/assignment/core.py:1060
#, python-format
msgid "Domain (%s)"
msgstr "域 (%s)"

#: keystone/assignment/core.py:1062
msgid "Unknown Target"
msgstr "目标未知"

#: keystone/assignment/core.py:1518
msgid "Update of `domain_id` is not allowed."
msgstr "不允许更新“domain_id”。"

#: keystone/assignment/core.py:1743
msgid "Domain specific roles are not supported in the V8 role driver"
msgstr "V8 角色驱动程序中不支持特定于域的角色"

#: keystone/assignment/V8_backends/sql.py:287
#: keystone/assignment/backends/sql.py:137
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr "无法除去尚未授予的角色 %s"

#: keystone/assignment/V8_backends/sql.py:363
#: keystone/assignment/backends/sql.py:213
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr "遇到意外的指派类型 %s"

#: keystone/auth/controllers.py:60
#, python-format
msgid ""
"Direct import of auth plugin %(name)r is deprecated as of Liberty in favor "
"of its entrypoint from %(namespace)r and may be removed in N."
msgstr ""
"自 Liberty 开始，已不推荐直接导入认证插件 %(name)r（为了支持它在 %(namespace)r 中的入口点），并且可能在 N 中移除。"

#: keystone/auth/controllers.py:121
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has conflicting "
"values %(new)s and %(old)s"
msgstr "无法协调身份属性 %(attribute)s，因为它具有冲突值%(new)s 和 %(old)s"

#: keystone/auth/controllers.py:182
msgid "Domain name cannot contain reserved characters."
msgstr "域名不能包含保留字符。"

#: keystone/auth/controllers.py:205
msgid "Project name cannot contain reserved characters."
msgstr "项目名称不能包含保留字符。"

#: keystone/auth/controllers.py:355 keystone/middleware/auth.py:130
msgid "Scoping to both domain and project is not allowed"
msgstr "不允许同时将作用域限定到域和项目"

#: keystone/auth/controllers.py:358
msgid "Scoping to both domain and trust is not allowed"
msgstr "不允许同时将作用域限定到域和信任"

#: keystone/auth/controllers.py:361
msgid "Scoping to both project and trust is not allowed"
msgstr "不允许同时将作用域限定到项目和信任"

#: keystone/auth/controllers.py:530
msgid "User not found"
msgstr "找不到用户"

#: keystone/auth/controllers.py:644
msgid "A project-scoped token is required to produce a service catalog."
msgstr "产生服务目录时需要项目范围的令牌。"

#: keystone/auth/plugins/external.py:42
msgid "No authenticated user"
msgstr "不存在任何已认证的用户"

#: keystone/auth/plugins/external.py:52
#, python-format
msgid "Unable to lookup user %s"
msgstr "无法查找用户 %s"

#: keystone/auth/plugins/external.py:100
msgid "auth_type is not Negotiate"
msgstr "auth_type 不是“Negotiate”"

#: keystone/auth/plugins/mapped.py:246
msgid ""
"Could not map user while setting ephemeral user identity. Either mapping "
"rules must specify user id/name or REMOTE_USER environment variable must be "
"set."
msgstr "设置临时用户身份时未能映射用户。映射规则必须指定用户标识/用户名，或者必须设置 REMOTE_USER 环境变量。"

#: keystone/auth/plugins/oauth1.py:46
msgid "Access token is expired"
msgstr "访问令牌已过期"

#: keystone/auth/plugins/oauth1.py:60
msgid "Could not validate the access token"
msgstr "未能验证访问令牌"

#: keystone/auth/plugins/password.py:39
msgid "Invalid username or password"
msgstr "无效用户名或密码"

#: keystone/auth/plugins/token.py:70 keystone/token/controllers.py:160
msgid "rescope a scoped token"
msgstr "请重新确定带范围的令牌的范围"

#: keystone/auth/plugins/totp.py:96
msgid "Invalid username or TOTP passcode"
msgstr "无效用户名或 TOTP 密码"

#: keystone/catalog/controllers.py:215
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr "指定的区域标识有冲突：“%(url_id)s”不等于“%(ref_id)s”"

#: keystone/catalog/core.py:149 keystone/common/ldap/core.py:1411
#, python-format
msgid "Duplicate ID, %s."
msgstr "标识 %s 重复。"

#: keystone/catalog/backends/sql.py:389
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr "在项目 %(project_id)s 中找不到端点 %(endpoint_id)s"

#: keystone/catalog/backends/sql.py:492
msgid "Endpoint Group Project Association not found"
msgstr "找不到端点组项目关联"

#: keystone/cmd/cli.py:173
msgid ""
"Either --bootstrap-password argument or OS_BOOTSTRAP_PASSWORD must be set."
msgstr "必须设置 --bootstrap-password 自变量或 OS_BOOTSTRAP_PASSWORD。"

#: keystone/cmd/cli.py:586
msgid "At least one option must be provided"
msgstr "必须至少提供一个选项"

#: keystone/cmd/cli.py:593
msgid "--all option cannot be mixed with other options"
msgstr "--all 选项不能与其他选项一起使用"

#: keystone/cmd/cli.py:600
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr "--domain-name 指定的“%(name)s”是未知域"

#: keystone/cmd/cli.py:679 keystone/tests/unit/test_cli.py:411
msgid ""
"At least one option must be provided, use either --all or --domain-name"
msgstr "必须至少提供一个选项，请使用 --all 或 --domain-name"

#: keystone/cmd/cli.py:685 keystone/tests/unit/test_cli.py:427
msgid "The --all option cannot be used with the --domain-name option"
msgstr "--all 选项不能与 --domain-name 选项配合使用"

#: keystone/cmd/cli.py:710 keystone/tests/unit/test_cli.py:444
#, python-format
msgid ""
"Invalid domain name: %(domain)s found in config file name: %(file)s - "
"ignoring this file."
msgstr "在配置文件名 %(file)s 中找到的域名 %(domain)s 无效 - 正在忽略此文件。"

#: keystone/cmd/cli.py:718 keystone/tests/unit/test_cli.py:385
#, python-format
msgid ""
"Domain: %(domain)s already has a configuration defined - ignoring file: "
"%(file)s."
msgstr "域 %(domain)s 已定义配置 - 正在忽略以下文件：%(file)s。"

#: keystone/cmd/cli.py:732
#, python-format
msgid ""
"Error parsing configuration file for domain: %(domain)s, file: %(file)s."
msgstr "解析域 %(domain)s 的配置文件时出错，文件为 %(file)s。"

#: keystone/cmd/cli.py:783
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr "找不到指定的域配置目录：%s"

#: keystone/cmd/cli.py:803
msgid ""
"Unable to access the keystone database, please check it is configured "
"correctly."
msgstr "无法访问 keystone 数据库，请检查它是否正确配置。"

#: keystone/cmd/cli.py:866
#, python-format
msgid "Error while parsing rules %(path)s: %(err)s"
msgstr "解析规则 %(path)s 时出错：%(err)s"

#: keystone/cmd/cli.py:875
#, python-format
msgid "Error while opening file %(path)s: %(err)s"
msgstr "打开文件 %(path)s 时出错：%(err)s"

#: keystone/cmd/cli.py:885
#, python-format
msgid "Error while parsing line: '%(line)s': %(err)s"
msgstr "解析行“%(line)s”时出错：%(err)s"

#: keystone/common/authorization.py:61 keystone/common/wsgi.py:67
#, python-format
msgid "token reference must be a KeystoneToken type, got: %s"
msgstr "令牌引用必须为 KeystoneToken 类型，但收到：%s"

#: keystone/common/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr "%s 不能为空。"

#: keystone/common/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr "%(property_name)s 不能少于 %(min_length)s 个字符。"

#: keystone/common/clean.py:31
#, python-format
msgid ""
"%(property_name)s should not be greater than %(max_length)s characters."
msgstr "%(property_name)s 不应该超过 %(max_length)s 个字符。"

#: keystone/common/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr "%(property_name)s 不在 %(display_expected_type)s 之中"

#: keystone/common/controller.py:349 keystone/common/controller.py:377
#: keystone/identity/core.py:595 keystone/resource/core.py:1145
#, python-format
msgid "Expected dict or list: %s"
msgstr "期望字典或者列表: %s"

#: keystone/common/controller.py:390
msgid "Marker could not be found"
msgstr "找不到标记符"

#: keystone/common/controller.py:401
msgid "Invalid limit value"
msgstr "限制值无效"

#: keystone/common/controller.py:705
msgid "Cannot change Domain ID"
msgstr "无法更改域标识"

#: keystone/common/controller.py:751
msgid ""
"You have tried to create a resource using the admin token. As this token is "
"not within a domain you must explicitly include a domain for this resource "
"to belong to."
msgstr "您已尝试使用管理员令牌创建资源。因为此令牌不在域中，所以您必须显式添加域以使此资源成为其成员。"

#: keystone/common/dependency.py:65
#, python-format
msgid "Unregistered dependency: %(name)s for %(targets)s"
msgstr "已针对 %(targets)s 注销依赖关系 %(name)s"

#: keystone/common/driver_hints.py:38
msgid ""
"Cannot truncate a driver call without hints list as first parameter after "
"self "
msgstr "在没有将 hints list 用作 self 后面的第一个参数的情况下，无法截断驱动程序调用 "

#: keystone/common/json_home.py:76
#, python-format
msgid "Unexpected status requested for JSON Home response, %s"
msgstr "请求 JSON 主页响应时处于意外状态，%s"

#: keystone/common/manager.py:82
#, python-format
msgid ""
"Direct import of driver %(name)r is deprecated as of Liberty in favor of its "
"entrypoint from %(namespace)r and may be removed in N."
msgstr ""
"自 Liberty 开始，已不推荐直接导入驱动程序 %(name)r（为了支持它在 %(namespace)r 中的入口点），并且可能在 N 中移除。"

#: keystone/common/tokenless_auth.py:73
msgid "Neither Project Domain ID nor Project Domain Name was provided."
msgstr "既未提供项目域标识，也未提供项目域名。"

#: keystone/common/tokenless_auth.py:165
msgid ""
"User auth cannot be built due to missing either user id, or user name with "
"domain id, or user name with domain name."
msgstr "由于缺少用户标识、具有域标识的用户名或者具有域名的用户名，因此无法构建用户认证。"

#: keystone/common/utils.py:63
msgid ""
"Length of transformable resource id > 64, which is max allowed characters"
msgstr "可变换资源标识的长度超过 64 个字符（允许的最大字符数）。"

#: keystone/common/utils.py:192 keystone/credential/controllers.py:44
msgid "Invalid blob in credential"
msgstr "凭证中的 BLOB 无效"

#: keystone/common/wsgi.py:208
msgid "Query string is not UTF-8 encoded"
msgstr "查询字符串不是采用 UTF-8 编码"

#: keystone/common/wsgi.py:341
#, python-format
msgid "%s field is required and cannot be empty"
msgstr "%s 字段是必填字段，不能为空"

#: keystone/common/wsgi.py:353
#, python-format
msgid "%s field(s) cannot be empty"
msgstr "%s 字段不能为空"

#: keystone/common/wsgi.py:548
msgid "The resource could not be found."
msgstr "找不到该资源。"

#: keystone/common/kvs/core.py:88
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr "对于键 %(target)s，发生锁定超时"

#: keystone/common/kvs/core.py:123
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr "已配置 KVS 区域 %s。无法重新配置。"

#: keystone/common/kvs/core.py:166
#, python-format
msgid "Key Value Store not configured: %s"
msgstr "未配置键值存储：%s"

#: keystone/common/kvs/core.py:219
msgid "`key_mangler` option must be a function reference"
msgstr "“key_mangler”选项必须为函数引用"

#: keystone/common/kvs/core.py:376
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr "锁定键必须与目标键匹配：%(lock)s != %(target)s"

#: keystone/common/kvs/core.py:380
msgid "Must be called within an active lock context."
msgstr "必须在处于活动状态的锁定上下文内调用。"

#: keystone/common/kvs/backends/memcached.py:68
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr "已达到对 %s 的最大锁定尝试次数。"

#: keystone/common/kvs/backends/memcached.py:109
#, python-format
msgid ""
"Backend `%(backend)s` is not a valid memcached backend. Valid backends: "
"%(backend_list)s"
msgstr "后端“%(backend)s”不是有效的 memcached 后端。有效后端：%(backend_list)s"

#: keystone/common/kvs/backends/memcached.py:185
msgid "`key_mangler` functions must be callable."
msgstr "“key_mangler”函数必须可调用。"

#: keystone/common/ldap/core.py:199
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr "LDAP deref 选项 %(option)s 无效。请选择下列其中一项：%(options)s"

#: keystone/common/ldap/core.py:209
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr "LDAP TLS 证书选项 %(option)s 无效。请选择下列其中一项：%(options)s"

#: keystone/common/ldap/core.py:221
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr "无效的 LDAP作用域: %(scope)s.  选择以下选项之一: %(options)s"

#: keystone/common/ldap/core.py:591
msgid "Invalid TLS / LDAPS combination"
msgstr "无效的 TLS / LDAPS 组合"

#: keystone/common/ldap/core.py:596
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr "无效的LDAP TLS_AVAIL  选项: %s.TLS无效"

#: keystone/common/ldap/core.py:606
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr "tls_cacertfile %s 未找到或者不是一个文件"

#: keystone/common/ldap/core.py:618
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr "tls_cacertdir %s 未找到或者不是一个目录"

#: keystone/common/ldap/core.py:1333
#, python-format
msgid "ID attribute %(id_attr)s not found in LDAP object %(dn)s"
msgstr "在 LDAP 对象 %(dn)s 中，找不到标识属性 %(id_attr)s"

#: keystone/common/ldap/core.py:1378
#, python-format
msgid "LDAP %s create"
msgstr "LDAP %s 创建"

#: keystone/common/ldap/core.py:1383
#, python-format
msgid "LDAP %s update"
msgstr "LDAP %s 更新"

#: keystone/common/ldap/core.py:1388
#, python-format
msgid "LDAP %s delete"
msgstr "LDAP %s 删除"

#: keystone/common/ldap/core.py:1400
#, python-format
msgid "Duplicate name, %s."
msgstr "名称 %s 重复。"

#: keystone/common/ldap/core.py:1557
msgid ""
"Disabling an entity where the 'enable' attribute is ignored by configuration."
msgstr "正在禁用实体，在此情况下，“enable”属性已由配置忽略。"

#: keystone/common/ldap/core.py:1568
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr "无法更改 %(option_name)s %(attr)s"

#: keystone/common/ldap/core.py:1655
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr "成员 %(member)s 已属于组 %(group)s"

#: keystone/common/sql/core.py:413
msgid "Duplicate Entry"
msgstr "重复条目"

#: keystone/common/sql/core.py:429
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr "尝试存储 %s 时发生意外错误"

#: keystone/common/sql/migration_helpers.py:167
msgid "Unable to downgrade schema"
msgstr "无法对模式进行降级"

#: keystone/common/sql/migration_helpers.py:185
#: keystone/common/sql/migration_helpers.py:231
#, python-format
msgid "%s extension does not exist."
msgstr "%s 扩展不存在。"

#: keystone/common/validation/__init__.py:44
#, python-format
msgid ""
"validated expected to find %(param_name)r in function signature for "
"%(func_name)r."
msgstr "已验证期望在 %(func_name)r 的函数签名中查找 %(param_name)r"

#: keystone/common/validation/validators.py:53
#, python-format
msgid "Invalid input for field '%(path)s': %(message)s"
msgstr ""

#: keystone/contrib/admin_crud/core.py:28
msgid ""
"Remove admin_crud_extension from the paste pipeline, the admin_crud "
"extension is now always available. Updatethe [pipeline:admin_api] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"从粘贴管道移除 admin_crud_extension，admin_crud 扩展现在始终可用。对 keystone-paste.ini 中的 "
"[pipeline:admin_api] 节进行相应更新，因为它将会在 O 发行版中移除。"

#: keystone/contrib/ec2/controllers.py:80 keystone/contrib/s3/core.py:111
#: keystone/contrib/s3/core.py:114
msgid "Invalid EC2 signature."
msgstr "无效 EC2 签名。"

#: keystone/contrib/ec2/controllers.py:83
#: keystone/contrib/ec2/controllers.py:87
#: keystone/contrib/ec2/controllers.py:125
msgid "EC2 signature not supplied."
msgstr "未提供 EC2 签名。"

#: keystone/contrib/ec2/controllers.py:159
msgid "User not valid for tenant."
msgstr "用户做为租户是无效的。"

#: keystone/contrib/ec2/controllers.py:260
msgid "EC2 access key not found."
msgstr "找不到 EC2 访问密钥。"

#: keystone/contrib/ec2/controllers.py:326
msgid "Token belongs to another user"
msgstr "令牌属于另一用户"

#: keystone/contrib/ec2/controllers.py:354
msgid "Credential belongs to another user"
msgstr "凭证属于另一用户"

#: keystone/contrib/endpoint_filter/routers.py:29
msgid ""
"Remove endpoint_filter_extension from the paste pipeline, the endpoint "
"filter extension is now always available. Update the [pipeline:api_v3] "
"section in keystone-paste.ini accordingly as it will be removed in the O "
"release."
msgstr ""
"从粘贴管道移除 endpoint_filter_extension，端点过滤器扩展现在始终可用。对 keystone-paste.ini 中的  "
"[pipeline:api_v3] 节进行相应更新，因为它将会在 O 发行版中移除。"

#: keystone/contrib/federation/routers.py:27
msgid ""
"Remove federation_extension from the paste pipeline, the federation "
"extension is now always available. Update the [pipeline:api_v3] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"从粘贴管道移除 federation_extension，联合扩展现在始终可用。对 keystone-paste.ini 中的  "
"[pipeline:api_v3] 节进行相应更新，因为它将会在 O 发行版中移除。"

#: keystone/contrib/oauth1/routers.py:29
msgid ""
"Remove oauth1_extension from the paste pipeline, the oauth1 extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"从粘贴管道移除 oauth1_extension，oauth1 扩展现在始终可用。对 keystone-paste.ini 中的  "
"[pipeline:api_v3] 节进行相应更新，因为它将会在 O 发行版中移除。"

#: keystone/contrib/revoke/routers.py:27
msgid ""
"Remove revoke_extension from the paste pipeline, the revoke extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"从粘贴管道移除 revoke_extension，撤销扩展现在始终可用。对 keystone-paste.ini 中的  "
"[pipeline:api_v3] 节进行相应更新，因为它将会在 O 发行版中移除。"

#: keystone/contrib/s3/core.py:82
msgid "Credential signature mismatch"
msgstr "凭据签名不匹配"

#: keystone/contrib/simple_cert/routers.py:27
msgid ""
"Remove simple_cert from the paste pipeline, the PKI and PKIz token providers "
"are now deprecated and simple_cert was only used insupport of these token "
"providers. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"从粘贴管道移除 simple_cert，现在已不推荐使用 PKI 和 PKIz 令牌，simple_cert 仅用于支持这些令牌提供程序。对 "
"keystone-paste.ini 中的 [pipeline:api_v3] 节进行相应更新，因为它将会在 O 发行版中移除。"

#: keystone/contrib/user_crud/core.py:28
msgid ""
"Remove user_crud_extension from the paste pipeline, the user_crud extension "
"is now always available. Updatethe [pipeline:public_api] section in keystone-"
"paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"从粘贴管道移除 user_crud_extension，user_crud 扩展现在始终可用。对 keystone-paste.ini 中的 "
"[pipeline:admin_api] 节进行相应更新，因为它将会在 O 发行版中移除。"

#: keystone/endpoint_policy/core.py:264
#, python-format
msgid "No policy is associated with endpoint %(endpoint_id)s."
msgstr "没有任何策略与端点 %(endpoint_id)s 关联。"

#: keystone/federation/controllers.py:269
msgid "Request must have an origin query parameter"
msgstr "请求必须具有源查询参数"

#: keystone/federation/controllers.py:278
#, python-format
msgid "%(host)s is not a trusted dashboard host"
msgstr "%(host)s 不是可信的仪表板主机"

#: keystone/federation/controllers.py:309
msgid "Missing entity ID from environment"
msgstr "环境中缺少实体标识"

#: keystone/federation/controllers.py:357
msgid "Use a project scoped token when attempting to create a SAML assertion"
msgstr "当尝试创建 SAML 断言时，请使用项目范围的令牌"

#: keystone/federation/idp.py:486
#, python-format
msgid "Cannot open certificate %(cert_file)s. Reason: %(reason)s"
msgstr "无法打开证书 %(cert_file)s。原因：%(reason)s"

#: keystone/federation/idp.py:552
msgid "Ensure configuration option idp_entity_id is set."
msgstr "请确保设置了配置选项 idp_entity_id。"

#: keystone/federation/idp.py:555
msgid "Ensure configuration option idp_sso_endpoint is set."
msgstr "请确保设置了配置选项 idp_sso_endpoint。"

#: keystone/federation/idp.py:574
msgid ""
"idp_contact_type must be one of: [technical, other, support, administrative "
"or billing."
msgstr ""
"idp_contact_type 必须是下列其中一项：technical、other、support、administrative 或 billing。"

#: keystone/federation/utils.py:234
msgid "Federation token is expired"
msgstr "联合令牌已到期"

#: keystone/federation/utils.py:286
msgid "Could not find Identity Provider identifier in environment"
msgstr "在环境中，找不到“身份提供者”标识"

#: keystone/federation/utils.py:290
msgid ""
"Incoming identity provider identifier not included among the accepted "
"identifiers."
msgstr "新的“身份提供者”标识未包含在已接受的标识中。"

#: keystone/federation/utils.py:585
#, python-format
msgid "User type %s not supported"
msgstr "用户类型 %s 不受支持"

#: keystone/federation/utils.py:605
msgid ""
"Could not map any federated user properties to identity values. Check debug "
"logs or the mapping used for additional details."
msgstr "无法将任何联合用户属性映射至身份值。请检查调试日志或所使用的映射以获取其他信息。"

#: keystone/federation/utils.py:629
#, python-format
msgid ""
"Invalid rule: %(identity_value)s. Both 'groups' and 'domain' keywords must "
"be specified."
msgstr "规则 %(identity_value)s 无效。必须同时指定关键字“groups”和“domain”。"

#: keystone/federation/utils.py:854
#, python-format
msgid "Identity Provider %(idp)s is disabled"
msgstr "身份提供者 %(idp)s 已禁用"

#: keystone/federation/utils.py:862
#, python-format
msgid "Service Provider %(sp)s is disabled"
msgstr "服务提供程序 %(sp)s 已禁用"

#: keystone/federation/backends/sql.py:182
#, python-format
msgid "Duplicate remote ID: %s"
msgstr "重复远程标识：%s"

#: keystone/federation/backends/sql.py:184
#, python-format
msgid "Duplicate entry: %s"
msgstr "重复条目：%s"

#: keystone/identity/controllers.py:74
msgid "Enabled field must be a boolean"
msgstr "已启用的字段必须为布尔值"

#: keystone/identity/controllers.py:103
msgid "Enabled field should be a boolean"
msgstr "已启用的字段应该为布尔值"

#: keystone/identity/core.py:265
#, python-format
msgid "Config API entity at /domains/%s/config"
msgstr "在 /domains/%s/config 配置 API 实体"

#: keystone/identity/core.py:271
#, python-format
msgid ""
"Exceeded attempts to register domain %(domain)s to use the SQL driver, the "
"last domain that appears to have had it is %(last_domain)s, giving up"
msgstr ""
"注册域 %(domain)s 以使用 SQL 驱动程序的尝试次数已超出限制，显示为进行此尝试的最后一个域为 %(last_domain)s，正在放弃"

#: keystone/identity/core.py:450 keystone/identity/backends/ldap.py:62
#: keystone/identity/backends/ldap.py:64 keystone/identity/backends/ldap.py:70
#: keystone/identity/backends/ldap.py:72 keystone/identity/backends/sql.py:210
#: keystone/identity/backends/sql.py:212
msgid "Invalid user / password"
msgstr "用户/密码无效"

#: keystone/identity/core.py:895
#, python-format
msgid "User is disabled: %s"
msgstr "用户已禁用：%s"

#: keystone/identity/core.py:928 keystone/resource/core.py:375
msgid ""
"update of domain_id is deprecated as of Mitaka and will be removed in O."
msgstr "从 Mitaka 开始，已不推荐更新 domain_id，它将在 O 发行版中移除。"

#: keystone/identity/core.py:947
msgid "Cannot change user ID"
msgstr "无法更改用户标识"

#: keystone/identity/backends/ldap.py:35
#, python-format
msgid ""
"%s for the LDAP identity backend has been deprecated in the Mitaka release "
"in favor of read-only identity LDAP access. It will be removed in the \"O\" "
"release."
msgstr "在 Mitaka 发行版中，已不推荐使用 LDAP 身份后端的 %s （以支持只读身份 LDAP 访问）。它将在“O”发行版中移除。"

#: keystone/identity/backends/ldap.py:106
msgid "Cannot change user name"
msgstr "无法更改用户名"

#: keystone/identity/backends/ldap.py:214 keystone/identity/backends/sql.py:292
#: keystone/identity/backends/sql.py:310
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr "在组“%(group_id)s”中找不到用户“%(user_id)s”"

#: keystone/identity/backends/ldap.py:366
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr "用户%(user_id)s 已是组 %(group_id)s 的成员"

#: keystone/models/token_model.py:62
msgid "Found invalid token: scoped to both project and domain."
msgstr "发现无效令牌：范围同时为项目和域。"

#: keystone/oauth1/controllers.py:126
msgid "Cannot list request tokens with a token issued via delegation."
msgstr "无法列示带有通过代理发出的令牌的请求令牌。"

#: keystone/oauth1/controllers.py:187 keystone/oauth1/backends/sql.py:256
msgid "User IDs do not match"
msgstr "用户ID不匹配"

#: keystone/oauth1/controllers.py:243
msgid "Invalid signature"
msgstr "签名无效"

#: keystone/oauth1/controllers.py:294 keystone/oauth1/controllers.py:372
msgid "Request token is expired"
msgstr "请求令牌已过期"

#: keystone/oauth1/controllers.py:308
msgid "There should not be any non-oauth parameters"
msgstr "不应该存在任何非 oauth 参数"

#: keystone/oauth1/controllers.py:312
msgid "provided consumer key does not match stored consumer key"
msgstr "提供的用户密钥与存储的用户密钥不匹配"

#: keystone/oauth1/controllers.py:316
msgid "provided verifier does not match stored verifier"
msgstr "提供的验证器与存储的验证器不匹配"

#: keystone/oauth1/controllers.py:320
msgid "provided request key does not match stored request key"
msgstr "提供的请求密钥与存储的请求密钥不匹配"

#: keystone/oauth1/controllers.py:324
msgid "Request Token does not have an authorizing user id"
msgstr "请求令牌没有授权用户标识"

#: keystone/oauth1/controllers.py:361
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr "无法对带有通过代理发出的令牌的请求令牌授权。"

#: keystone/oauth1/controllers.py:388
msgid "authorizing user does not have role required"
msgstr "授权用户没有必需的角色"

#: keystone/oauth1/controllers.py:401
msgid "User is not a member of the requested project"
msgstr "用户不是所请求项目的成员"

#: keystone/oauth1/backends/sql.py:91
msgid "Consumer not found"
msgstr "找不到使用者"

#: keystone/oauth1/backends/sql.py:177
msgid "Request token not found"
msgstr "找不到请求令牌"

#: keystone/oauth1/backends/sql.py:237
msgid "Access token not found"
msgstr "找不到访问令牌"

#: keystone/resource/controllers.py:94
msgid "The creation of projects acting as domains is not allowed in v2."
msgstr "不允许在 V2 中创建充当域的项目。"

#: keystone/resource/controllers.py:284
msgid ""
"Cannot use parents_as_list and parents_as_ids query params at the same time."
msgstr "无法同时使用 parents_as_list 和 parents_as_ids 查询参数。"

#: keystone/resource/controllers.py:290
msgid ""
"Cannot use subtree_as_list and subtree_as_ids query params at the same time."
msgstr "无法同时使用 subtree_as_list 和 subtree_as_ids 查询参数。"

#: keystone/resource/core.py:106
#, python-format
msgid "Max hierarchy depth reached for %s branch."
msgstr "已达到 %s 分支的最大层深度。"

#: keystone/resource/core.py:123
msgid "Multiple domains are not supported"
msgstr "多个域不受支持"

#: keystone/resource/core.py:129
msgid "only root projects are allowed to act as domains."
msgstr "只允许根项目充当域。"

#: keystone/resource/core.py:152
#, python-format
msgid ""
"Cannot create project, since its parent (%(domain_id)s) is acting as a "
"domain, but project's specified parent_id (%(parent_id)s) does not match "
"this domain_id."
msgstr ""
"无法创建项目，因为其父代 (%(domain_id)s) 正充当域，但该项目的指定 parent_id (%(parent_id)s) 与此 "
"domain_id 不匹配。"

#: keystone/resource/core.py:163
#, python-format
msgid ""
"Cannot create project, since it specifies its owner as domain %(domain_id)s, "
"but specifies a parent in a different domain (%(parent_domain_id)s)."
msgstr ""
"无法创建项目，因为它将其所有者指定为域 %(domain_id)s，但在另一个域 (%(parent_domain_id)s) 中指定了父代。"

#: keystone/resource/core.py:183
#, python-format
msgid "cannot create a project in a branch containing a disabled project: %s"
msgstr "无法在包含已禁用项目的分支中创建项目：%s"

#: keystone/resource/core.py:191
#, python-format
msgid ""
"%(entity)s name cannot contain the following reserved characters: %(chars)s"
msgstr "%(entity)s 名称不能包含以下保留字符：%(chars)s"

#: keystone/resource/core.py:201
#, python-format
msgid ""
"it is not permitted to have two projects acting as domains with the same "
"name: %s"
msgstr "不允许两个同名项目充当域：%s"

#: keystone/resource/core.py:205
#, python-format
msgid ""
"it is not permitted to have two projects with the same name in the same "
"domain : %s"
msgstr ""

#: keystone/resource/core.py:262
#, python-format
msgid "Domain is disabled: %s"
msgstr "域已禁用：%s"

#: keystone/resource/core.py:279
#, python-format
msgid "Domain cannot be named %s"
msgstr "无法将域命名为 %s"

#: keystone/resource/core.py:282
#, python-format
msgid "Domain cannot have ID %s"
msgstr "域不能具有标识 %s"

#: keystone/resource/core.py:297
#, python-format
msgid "Project is disabled: %s"
msgstr "项目已禁用：%s"

#: keystone/resource/core.py:304
#, python-format
msgid "Cannot enable project %s since it has disabled parents"
msgstr "无法启用项目 %s，因为它具有已禁用的父代"

#: keystone/resource/core.py:340
msgid "Update of `parent_id` is not allowed."
msgstr "不允许更新“parent_id”。"

#: keystone/resource/core.py:345
msgid "Update of `is_domain` is not allowed."
msgstr "不允许更新“is_domain”。"

#: keystone/resource/core.py:359
msgid "Update of domain_id of projects acting as domains is not allowed."
msgstr "不允许更新充当域的项目的 domain_id。"

#: keystone/resource/core.py:366
msgid "Update of domain_id is only allowed for root projects."
msgstr "只允许更新根项目的 domain_id。"

#: keystone/resource/core.py:371
msgid "Cannot update domain_id of a project that has children."
msgstr "无法更新具有子代的项目的 domain_id。"

#: keystone/resource/core.py:396
#, python-format
msgid ""
"Cannot disable project %(project_id)s since its subtree contains enabled "
"projects."
msgstr "无法禁用项目 %(project_id)s，因为它的子树包含已启用的项目。"

#: keystone/resource/core.py:443
msgid "Cascade update is only allowed for enabled attribute."
msgstr "只允许对已启用的属性执行级联更新。"

#: keystone/resource/core.py:507
#, python-format
msgid ""
"cannot delete an enabled project acting as a domain. Please disable the "
"project %s first."
msgstr "无法删除充当域的已启用项目。请先禁用项目 %s。"

#: keystone/resource/core.py:513
#, python-format
msgid ""
"Cannot delete the project %s since it is not a leaf in the hierarchy. Use "
"the cascade option if you want to delete a whole subtree."
msgstr "无法删除项目 %s，因为它不是该层次结构中的支叶。如果要删除整个子树，请使用级联选项。"

#: keystone/resource/core.py:526
#, python-format
msgid ""
"Cannot delete project %(project_id)s since its subtree contains enabled "
"projects."
msgstr "无法删除项目 %(project_id)s，因为其子树包含已启用的项目。"

#: keystone/resource/core.py:554
msgid "Project field is required and cannot be empty."
msgstr "项目字段是必填字段，不得为空。"

#: keystone/resource/core.py:795
msgid "Cannot delete a domain that is enabled, please disable it first."
msgstr "无法删除已启用的域，请先禁用该域。"

#: keystone/resource/core.py:1570
msgid "No options specified"
msgstr "无选项指定"

#: keystone/resource/core.py:1576
#, python-format
msgid ""
"The value of group %(group)s specified in the config should be a dictionary "
"of options"
msgstr "在配置中指定的组 %(group)s 的值应该是选项的字典"

#: keystone/resource/core.py:1600
#, python-format
msgid ""
"Option %(option)s found with no group specified while checking domain "
"configuration request"
msgstr "在检查域配置请求时，找到选项 %(option)s，但未指定任何组"

#: keystone/resource/core.py:1607
#, python-format
msgid "Group %(group)s is not supported for domain specific configurations"
msgstr "特定于域的配置不支持组 %(group)s"

#: keystone/resource/core.py:1614
#, python-format
msgid ""
"Option %(option)s in group %(group)s is not supported for domain specific "
"configurations"
msgstr "特定于域的配置不支持组 %(group)s 中的选项 %(option)s"

#: keystone/resource/core.py:1666
msgid "An unexpected error occurred when retrieving domain configs"
msgstr "检索域配置时发生意外错误"

#: keystone/resource/core.py:1745 keystone/resource/core.py:1828
#: keystone/resource/core.py:1898 keystone/resource/config_backends/sql.py:76
#, python-format
msgid "option %(option)s in group %(group)s"
msgstr "组 %(group)s 中的选项 %(option)s"

#: keystone/resource/core.py:1748 keystone/resource/core.py:1833
#: keystone/resource/core.py:1894
#, python-format
msgid "group %(group)s"
msgstr "组 %(group)s"

#: keystone/resource/core.py:1750
msgid "any options"
msgstr "任何选项"

#: keystone/resource/core.py:1793
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, so that, and only "
"that, option must be specified  in the config"
msgstr "正在尝试更新组 %(group)s 中的选项 %(option)s，因此仅存在以下要求：必须在配置中指定选项"

#: keystone/resource/core.py:1798
#, python-format
msgid ""
"Trying to update group %(group)s, so that, and only that, group must be "
"specified in the config"
msgstr "正在尝试更新组 %(group)s，因此仅存在以下要求：必须在配置中指定组"

#: keystone/resource/core.py:1807
#, python-format
msgid ""
"request to update group %(group)s, but config provided contains group "
"%(group_other)s instead"
msgstr "请求更新组 %(group)s，但所提供配置反而包含组 %(group_other)s"

#: keystone/resource/core.py:1814
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, but config provided "
"contains option %(option_other)s instead"
msgstr "正在尝试更新组 %(group)s 中的选项 %(option)s，但所提供配置反而包含选项 %(option_other)s"

#: keystone/resource/core.py:2006
#, python-format
msgid "Group  %s not found in config"
msgstr "在配置中找不到组 %s。"

#: keystone/resource/core.py:2016
#, python-format
msgid ""
"Reading the default for option %(option)s in group %(group)s is not supported"
msgstr "系统不支持读取组 %(group)s 中的选项 %(option)s 的缺省值。"

#: keystone/revoke/controllers.py:33
#, python-format
msgid "invalid date format %s"
msgstr "日期格式 %s 无效"

#: keystone/revoke/core.py:156
msgid ""
"The revoke call must not have both domain_id and project_id. This is a bug "
"in the Keystone server. The current request is aborted."
msgstr "撤销调用不能同时具有 domain_id 和 project_id。这是 Keystone 服务器中的错误。当前请求已异常中止。"

#: keystone/revoke/core.py:226 keystone/token/provider.py:217
#: keystone/token/provider.py:256 keystone/token/provider.py:336
#: keystone/token/provider.py:343
msgid "Failed to validate token"
msgstr "token验证失败"

#: keystone/token/controllers.py:372
msgid "Tenant name cannot contain reserved characters."
msgstr "租户名称不能包含保留字符。"

#: keystone/token/controllers.py:392
#, python-format
msgid "Project ID not found: %(t_id)s"
msgstr "找不到项目标识：%(t_id)s"

#: keystone/token/controllers.py:396
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr "用户 %(u_id)s 没有授权给租户 %(t_id)s"

#: keystone/token/controllers.py:415 keystone/token/controllers.py:418
msgid "Token does not belong to specified tenant."
msgstr "令牌不属于指定的租户。"

#: keystone/token/provider.py:269 keystone/token/provider.py:293
msgid "No token in the request"
msgstr "请求中没有令牌。"

#: keystone/token/persistence/backends/kvs.py:132
#, python-format
msgid "Unknown token version %s"
msgstr "令牌版本 %s 未知"

#: keystone/token/providers/common.py:313
#: keystone/token/providers/common.py:445
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr "用户%(user_id)s 没有访问项目 %(project_id)s的权限"

#: keystone/token/providers/common.py:318
#: keystone/token/providers/common.py:450
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr "用户%(user_id)s对域%(domain_id)s没有任何访问权限"

#: keystone/token/providers/common.py:345
msgid "Trustor is disabled."
msgstr "Trustor被禁用"

#: keystone/token/providers/common.py:434
msgid "Trustee has no delegated roles."
msgstr "托管人没有任何已委派的角色。"

#: keystone/token/providers/common.py:496
#, python-format
msgid "Invalid audit info data type: %(data)s (%(type)s)"
msgstr "无效审计信息数据类型：%(data)s (%(type)s)"

#: keystone/token/providers/common.py:560
#: keystone/token/providers/common.py:587
msgid "The configured token provider does not support bind authentication."
msgstr "所配置的令牌提供者不支持绑定认证。"

#: keystone/token/providers/common.py:598
msgid "User is not a trustee."
msgstr "用户不是受托人。"

#: keystone/token/providers/common.py:665
msgid ""
"Attempting to use OS-FEDERATION token with V2 Identity Service, use V3 "
"Authentication"
msgstr "正在尝试将 OS-FEDERATION 令牌与 V2 身份服务配合使用，请使用 V3 认证"

#: keystone/token/providers/common.py:675
msgid "Non-default domain is not supported"
msgstr "非缺省域不受支持"

#: keystone/token/providers/common.py:679
msgid "Domain scoped token is not supported"
msgstr "作用域限定的令牌不受支持"

#: keystone/token/providers/pki.py:53 keystone/token/providers/pkiz.py:31
msgid "Unable to sign token."
msgstr "无法对令牌进行签名。"

#: keystone/token/providers/fernet/token_formatters.py:102
#, python-format
msgid "This is not a recognized Fernet token %s"
msgstr "这不是可识别的 Fernet 令牌 %s"

#: keystone/token/providers/fernet/token_formatters.py:198
#, python-format
msgid "This is not a recognized Fernet payload version: %s"
msgstr "这不是可识别的 Fernet 有效内容版本：%s"

#: keystone/trust/controllers.py:107
#, python-format
msgid "role %s is not defined"
msgstr "未定义角色 %s"

#: keystone/trust/controllers.py:131
msgid "Redelegation allowed for delegated by trust only"
msgstr "仅允许对“委派者”信任进行重新委派"

#: keystone/trust/controllers.py:164
msgid "The authenticated user should match the trustor."
msgstr "认证用户应匹配信任者。"

#: keystone/trust/controllers.py:169
msgid "At least one role should be specified."
msgstr "应该至少指定一个角色。"

#: keystone/trust/core.py:58
#, python-format
msgid ""
"Remaining redelegation depth of %(redelegation_depth)d out of allowed range "
"of [0..%(max_count)d]"
msgstr "其余重新委派深度 %(redelegation_depth)d 超出允许的范围 [0..%(max_count)d]"

#: keystone/trust/core.py:67
#, python-format
msgid ""
"Field \"remaining_uses\" is set to %(value)s while it must not be set in "
"order to redelegate a trust"
msgstr "字段“remaining_uses”已设置为 %(value)s，尽管为了重新委派信任，不能设置该字段"

#: keystone/trust/core.py:78
msgid "Requested expiration time is more than redelegated trust can provide"
msgstr "请求的到期时间超过重新委派的信任可提供的到期时间"

#: keystone/trust/core.py:88
msgid "Some of requested roles are not in redelegated trust"
msgstr "某些所请求角色未在重新委派的信任中"

#: keystone/trust/core.py:112
msgid "One of the trust agents is disabled or deleted"
msgstr "其中一个信任代理已禁用或删除"

#: keystone/trust/core.py:131
msgid "remaining_uses must be a positive integer or null."
msgstr "remaining_uses 必须为正整数或 Null。"

#: keystone/trust/core.py:137
#, python-format
msgid ""
"Requested redelegation depth of %(requested_count)d is greater than allowed "
"%(max_count)d"
msgstr "请求的重新委派深度 %(requested_count)d 超过允许的 %(max_count)d"

#: keystone/trust/core.py:144
msgid "remaining_uses must not be set if redelegation is allowed"
msgstr "如果允许重新委派，那么不能设置 remaining_uses"

#: keystone/trust/core.py:154
msgid ""
"Modifying \"redelegation_count\" upon redelegation is forbidden. Omitting "
"this parameter is advised."
msgstr "正在修改“redelegation_count”（当禁止重新委派时）。建议省略此参数。"
