# Translations template for swift.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the swift project.
#
# Translators:
# Pearl Yajing Tan(Seagate Tech) <pearl.y.tan@seagate.com>, 2014
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: swift VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2011-01-26 23:59+0000\n"
"PO-Revision-Date: 2019-04-08 16:55+0000\n"
"Last-Translator: Copied by Zanata <Unknown>\n"
"Language-Team: Chinese (China)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2019-05-11 13:01+0000\n"
"X-Generator: Launchpad (build 18962)\n"
"Language: zh_CN\n"
"Generated-By: Babel 2.0\n"

#: swift/account/auditor.py:52 swift/account/auditor.py:75
#, python-format
msgid ""
"Since %(time)s: Account audits: %(passed)s passed audit, %(failed)s failed "
"audit"
msgstr "时间%(time)s：账户审查：%(passed)s 审查通过, %(failed)s 审查失败"

#: swift/account/auditor.py:100 swift/container/auditor.py:103
#, python-format
msgid "Audit passed for %s"
msgstr "%s 审计通过"

#: swift/account/auditor.py:103
#, python-format
msgid "ERROR Could not get account info %s"
msgstr "错误：无法获取账号信息%s"

#: swift/account/reaper.py:80 swift/container/updater.py:64
#, python-format
msgid "Loading account ring from %s"
msgstr "从 %s 加载帐户环"

#: swift/account/reaper.py:88 swift/obj/updater.py:57
#, python-format
msgid "Loading container ring from %s"
msgstr "从 %s 加载容器环"

#: swift/account/reaper.py:96
#, python-format
msgid "Loading object ring from %s"
msgstr "从 %s 加载对象环"

#: swift/account/reaper.py:106
msgid "Daemon started."
msgstr "守护进程已启动”"

#: swift/account/reaper.py:122
#, python-format
msgid "Begin devices pass: %s"
msgstr "开始设备扫描：%s"

#: swift/account/reaper.py:128 swift/common/utils.py:805
#: swift/obj/updater.py:74 swift/obj/updater.py:113
#, python-format
msgid "Skipping %s as it is not mounted"
msgstr "挂载失败 跳过%s"

#: swift/account/reaper.py:132
#, python-format
msgid "Devices pass completed: %.02fs"
msgstr "设备通过完成： %.02fs"

#: swift/account/reaper.py:215
#, python-format
msgid "Beginning pass on account %s"
msgstr "账号%s开始通过"

#: swift/account/reaper.py:238
#, python-format
msgid "Exception with containers for account %s"
msgstr "账号%s内容器出现异常"

#: swift/account/reaper.py:243
#, python-format
msgid "Exception with account %s"
msgstr "账号%s出现异常"

#: swift/account/reaper.py:244
#, python-format
msgid "Incomplete pass on account %s"
msgstr "账号%s未完成通过"

#: swift/account/reaper.py:246
#, python-format
msgid ", %s containers deleted"
msgstr "，删除容器%s"

#: swift/account/reaper.py:248
#, python-format
msgid ", %s objects deleted"
msgstr "，删除对象%s"

#: swift/account/reaper.py:250
#, python-format
msgid ", %s containers remaining"
msgstr "，剩余容器%s"

#: swift/account/reaper.py:253
#, python-format
msgid ", %s objects remaining"
msgstr "，剩余对象%s"

#: swift/account/reaper.py:255
#, python-format
msgid ", %s containers possibly remaining"
msgstr "，可能剩余容器%s"

#: swift/account/reaper.py:258
#, python-format
msgid ", %s objects possibly remaining"
msgstr "，可能剩余对象%s"

#: swift/account/reaper.py:261
msgid ", return codes: "
msgstr "，返回代码： "

#: swift/account/reaper.py:265
#, python-format
msgid ", elapsed: %.02fs"
msgstr "，耗时：%.02fs"

#: swift/account/reaper.py:320 swift/account/reaper.py:355
#: swift/account/reaper.py:406 swift/container/updater.py:277
#, python-format
msgid "Exception with %(ip)s:%(port)s/%(device)s"
msgstr "%(ip)s:%(port)s/%(device)s出现异常"

#: swift/account/reaper.py:333
#, python-format
msgid ""
"Exception with objects for container %(container)s for account %(account)s"
msgstr "账号%(account)s容器%(container)s的对象出现异常"

#: swift/account/server.py:309 swift/container/server.py:397
#: swift/obj/server.py:597
#, python-format
msgid "ERROR __call__ error with %(method)s %(path)s "
msgstr "%(method)s %(path)s出现错误__call__ error "

#: swift/auth/server.py:96 swift/common/middleware/swauth.py:94
msgid "No super_admin_key set in conf file! Exiting."
msgstr "conf文件中没有设置super_admin_key ！退出。"

#: swift/auth/server.py:152
#, python-format
msgid ""
"\n"
"THERE ARE ACCOUNTS IN YOUR auth.db THAT DO NOT BEGIN WITH YOUR NEW RESELLER\n"
"PREFIX OF \"%(reseller)s\".\n"
"YOU HAVE A FEW OPTIONS:\n"
"    1. RUN \"swift-auth-update-reseller-prefixes %(db_file)s "
"%(reseller)s\",\n"
"       \"swift-init auth-server restart\", AND\n"
"       \"swift-auth-recreate-accounts -K ...\" TO CREATE FRESH ACCOUNTS.\n"
"    OR\n"
"    2. REMOVE %(db_file)s, RUN \"swift-init auth-server restart\", AND RUN\n"
"       \"swift-auth-add-user ...\" TO CREATE BRAND NEW ACCOUNTS THAT WAY.\n"
"    OR\n"
"    3. ADD \"reseller_prefix = %(previous)s\" (WITHOUT THE QUOTES) TO YOUR\n"
"       proxy-server.conf IN THE [filter:auth] SECTION AND TO YOUR\n"
"       auth-server.conf IN THE [app:auth-server] SECTION AND RUN\n"
"       \"swift-init proxy-server restart\" AND \"swift-init auth-server "
"restart\"\n"
"       TO REVERT BACK TO YOUR PREVIOUS RESELLER PREFIX.\n"
"\n"
"    %(note)s\n"
"                    "
msgstr ""
"\n"
"你的 auth.db 有些账户未采用新的中间商(reseller)前缀\"%(reseller)s\"。\n"
"你有以下几个选择：\n"
"1. 运行 \"swift-auth-update-reseller-prefixes %(db_file)s %(reseller)s\",\n"
"    \"swift-init auth-server restart\", 和\n"
"    \"swift-auth-recreate-accounts -K ...\" 来创建新的帐户。\n"
"或者\n"
"2. 删除 %(db_file)s, 运行 \"swift-init auth-server restart\", 和运行\n"
"    \"swift-auth-add-user ...\" 来创建全新的帐户。\n"
"或者\n"
"3. 添加 \"reseller_prefix = %(previous)s\" (无引号) 到您的\n"
"     proxy-server.conf文件中的[filter:auth]段和 \n"
"     auth-server.conf 中的[app:auth-server]段，\n"
"      运行\"swift-init proxy-server restart\" 和 \n"
"     \"swift-init auth-server restart\"来恢复到您之前的中间商(reseller)前缀。\n"
"\n"
"%(note)s\n"
"                    "

#: swift/auth/server.py:173
msgid ""
"\n"
"    SINCE YOUR PREVIOUS RESELLER PREFIX WAS AN EMPTY STRING, IT IS NOT\n"
"    RECOMMENDED TO PERFORM OPTION 3 AS THAT WOULD MAKE SUPPORTING MULTIPLE\n"
"    RESELLERS MORE DIFFICULT.\n"
"                    "
msgstr ""
"\n"
"    由于您之前的中间商(reseller)前缀为空字符串，不推荐使用第3个选择，\n"
"否则难以支持多个中间商(reseller)。\n"
"                    "

#: swift/auth/server.py:178
msgid "CRITICAL: "
msgstr "关键： "

#: swift/auth/server.py:213
#, python-format
msgid "ERROR attempting to create account %(url)s: %(status)s %(reason)s"
msgstr "尝试创建帐户 %(url)s 产生错误：%(status)s %(reason)s"

#: swift/auth/server.py:346
#, python-format
msgid ""
"ALREADY EXISTS create_user(%(account)s, %(user)s, _, %(admin)s, "
"%(reseller_admin)s) [%(elapsed).02f]"
msgstr ""
"create_user(%(account)s，%(user)s，_，%(admin)s，%(reseller_admin)s) "
"[%(elapsed).02f]已经存在了"

#: swift/auth/server.py:364
#, python-format
msgid ""
"FAILED create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"[%(elapsed).02f]"
msgstr ""
"create_user(%(account)s，%(user)s，_，%(admin)s，%(reseller_admin)s) "
"[%(elapsed).02f]失败"

#: swift/auth/server.py:381
#, python-format
msgid ""
"SUCCESS create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"= %(url)s [%(elapsed).02f]"
msgstr ""
"create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) = "
"%(url)s [%(elapsed).02f]成功"

#: swift/auth/server.py:656
msgid "ERROR Unhandled exception in ReST request"
msgstr "错误 ReST请求有未处理的异常"

#: swift/common/bench.py:85
#, python-format
msgid "%(complete)s %(title)s [%(fail)s failures], %(rate).01f/s"
msgstr "%(complete)s %(title)s [%(fail)s failures], %(rate).01f/s"

#: swift/common/bench.py:97
msgid "CannotSendRequest.  Skipping..."
msgstr "CannotSendRequest异常。跳过..."

#: swift/common/bufferedhttp.py:96
#, python-format
msgid ""
"HTTP PERF: %(time).5f seconds to %(method)s %(host)s:%(port)s %(path)s)"
msgstr "HTTP PERF: %(time).5f 秒，%(method)s %(host)s:%(port)s %(path)s)"

#: swift/common/db.py:299
msgid "Broker error trying to rollback locked connection"
msgstr "服务器错误并尝试去回滚已经锁住的链接"

#: swift/common/db.py:754 swift/common/db.py:1221
#, python-format
msgid "Invalid pending entry %(file)s: %(entry)s"
msgstr "不可用的等待输入%(file)s: %(entry)s"

#: swift/common/db_replicator.py:84
#, python-format
msgid "ERROR reading HTTP response from %s"
msgstr "读取HTTP错误 响应来源%s"

#: swift/common/db_replicator.py:123
#, python-format
msgid ""
"Attempted to replicate %(count)d dbs in %(time).5f seconds (%(rate).5f/s)"
msgstr "%(time).5f seconds (%(rate).5f/s)尝试复制%(count)d dbs"

#: swift/common/db_replicator.py:129
#, python-format
msgid "Removed %(remove)d dbs"
msgstr "删除%(remove)d dbs"

#: swift/common/db_replicator.py:130
#, python-format
msgid "%(success)s successes, %(failure)s failures"
msgstr "%(success)s成功，%(failure)s失败"

#: swift/common/db_replicator.py:155
#, python-format
msgid "ERROR rsync failed with %(code)s: %(args)s"
msgstr "错误 rsync失败 %(code)s: %(args)s"

#: swift/common/db_replicator.py:205
#, python-format
msgid "Syncing chunks with %s"
msgstr "正在与 %s 同步数据块"

#: swift/common/db_replicator.py:213
#, python-format
msgid "ERROR Bad response %(status)s from %(host)s"
msgstr "失败响应错误%(status)s来自%(host)s"

#: swift/common/db_replicator.py:278
#, python-format
msgid "ERROR Unable to connect to remote server: %s"
msgstr "错误 无法连接到远程服务器：%s"

#: swift/common/db_replicator.py:316
#, python-format
msgid "Replicating db %s"
msgstr "正在复制数据库 %s"

#: swift/common/db_replicator.py:325 swift/common/db_replicator.py:479
#, python-format
msgid "Quarantining DB %s"
msgstr "隔离DB%s"

#: swift/common/db_replicator.py:328
#, python-format
msgid "ERROR reading db %s"
msgstr "错误 读取db %s"

#: swift/common/db_replicator.py:361
#, python-format
msgid "ERROR Remote drive not mounted %s"
msgstr "错误 远程驱动器无法挂载 %s"

#: swift/common/db_replicator.py:363
#, python-format
msgid "ERROR syncing %(file)s with node %(node)s"
msgstr "错误 同步 %(file)s 和 节点%(node)s"

#: swift/common/db_replicator.py:405
msgid "ERROR Failed to get my own IPs?"
msgstr "错误 无法获得我方IPs?"

#: swift/common/db_replicator.py:412
#, python-format
msgid "Skipping %(device)s as it is not mounted"
msgstr "因无法挂载跳过%(device)s"

#: swift/common/db_replicator.py:420
msgid "Beginning replication run"
msgstr "开始运行复制"

#: swift/common/db_replicator.py:425
msgid "Replication run OVER"
msgstr "复制运行结束"

#: swift/common/db_replicator.py:436
msgid "ERROR trying to replicate"
msgstr "尝试复制时发生错误"

#: swift/common/memcached.py:69
#, python-format
msgid "Timeout %(action)s to memcached: %(server)s"
msgstr "%(action)s超时 高性能内存对象缓存： %(server)s"

#: swift/common/memcached.py:72
#, python-format
msgid "Error %(action)s to memcached: %(server)s"
msgstr "%(action)s错误 高性能内存对象缓存： %(server)s"

#: swift/common/memcached.py:81
#, python-format
msgid "Error limiting server %s"
msgstr "服务器出现错误%s"

#: swift/common/utils.py:88
#, python-format
msgid "Unable to locate %s in libc.  Leaving as a no-op."
msgstr "无法查询到%s 保留为no-op"

#: swift/common/utils.py:255
msgid "STDOUT: Connection reset by peer"
msgstr "STDOUT：连接被peer重新设置"

#: swift/common/utils.py:257 swift/common/utils.py:260
#, python-format
msgid "STDOUT: %s"
msgstr "STDOUT: %s"

#: swift/common/utils.py:324
msgid "Connection refused"
msgstr "连接被拒绝"

#: swift/common/utils.py:326
msgid "Host unreachable"
msgstr "无法连接到主机"

#: swift/common/utils.py:328
msgid "Connection timeout"
msgstr "连接超时"

#: swift/common/utils.py:464
msgid "UNCAUGHT EXCEPTION"
msgstr "未捕获的异常"

#: swift/common/utils.py:511
msgid "Error: missing config file argument"
msgstr "错误：缺少配置文件参数"

#: swift/common/utils.py:516
#, python-format
msgid "Error: unable to locate %s"
msgstr "错误：无法查询到 %s"

#: swift/common/utils.py:743
#, python-format
msgid "Unable to read config file %s"
msgstr "无法读取配置文件 %s"

#: swift/common/utils.py:749
#, python-format
msgid "Unable to find %s config section in %s"
msgstr "无法在 %s 中找到 %s 配置部分"

#: swift/common/middleware/catch_errors.py:39
#, python-format
msgid "Error: %s"
msgstr "错误：%s"

#: swift/common/middleware/cname_lookup.py:91
#, python-format
msgid "Mapped %(given_domain)s to %(found_domain)s"
msgstr "集合%(given_domain)s到%(found_domain)s"

#: swift/common/middleware/cname_lookup.py:102
#, python-format
msgid "Following CNAME chain for  %(given_domain)s to %(found_domain)s"
msgstr "跟随CNAME链从%(given_domain)s到%(found_domain)s"

#: swift/common/middleware/ratelimit.py:172
msgid "Returning 497 because of blacklisting"
msgstr "因列入黑名单返回497"

#: swift/common/middleware/ratelimit.py:185
#, python-format
msgid ""
"Ratelimit sleep log: %(sleep)s for %(account)s/%(container)s/%(object)s"
msgstr "流量控制休眠日志：%(sleep)s for %(account)s/%(container)s/%(object)s"

#: swift/common/middleware/ratelimit.py:192
#, python-format
msgid "Returning 498 because of ops rate limiting (Max Sleep) %s"
msgstr "因 ops 频率限制(最大休眠数) %s 返回498"

#: swift/common/middleware/ratelimit.py:212
msgid "Warning: Cannot ratelimit without a memcached client"
msgstr "警告：缺失缓存客户端 无法控制流量"

#: swift/common/middleware/swauth.py:635
#, python-format
msgid ""
"ERROR: Exception while trying to communicate with "
"%(scheme)s://%(host)s:%(port)s/%(path)s"
msgstr "错误：尝试与 %(scheme)s://%(host)s:%(port)s/%(path)s 交互时出现异常"

#: swift/container/auditor.py:54 swift/container/auditor.py:78
#, python-format
msgid ""
"Since %(time)s: Container audits: %(pass)s passed audit, %(fail)s failed "
"audit"
msgstr "自%(time)s起：容器审计：%(pass)s通过审计, %(fail)s失败"

#: swift/container/auditor.py:68
msgid "Begin container audit \"once\" mode"
msgstr "开始容器审计\"once\" 模式"

#: swift/container/auditor.py:88
#, python-format
msgid "Container audit \"once\" mode completed: %.02fs"
msgstr "容器审计\"once\"模式完成：%.02fs"

#: swift/container/auditor.py:106
#, python-format
msgid "ERROR Could not get container info %s"
msgstr "错误：无法获取容器%s信息"

#: swift/container/server.py:114
#, python-format
msgid ""
"ERROR Account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): Response %(status)s %(reason)s"
msgstr ""
"出现错误 账号更新失败： %(ip)s:%(port)s/%(device)s (稍后尝试): 回应 %(status)s %(reason)s"

#: swift/container/server.py:122
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later)"
msgstr "错误 账号更新失败 %(ip)s:%(port)s/%(device)s (稍后尝试)"

#: swift/container/updater.py:78 swift/obj/replicator.py:492
#, python-format
msgid "%s is not mounted"
msgstr "%s未挂载"

#: swift/container/updater.py:97
#, python-format
msgid "ERROR with loading suppressions from %s: "
msgstr "执行下载压缩时发生错误%s "

#: swift/container/updater.py:107
msgid "Begin container update sweep"
msgstr "开始容器更新扫除"

#: swift/container/updater.py:140
#, python-format
msgid ""
"Container update sweep of %(path)s completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""
"通过路径%(path)s容器更新扫除完成：%(elapsed).02fs, %(success)s 成功, %(fail)s 失败, "
"%(no_change)s 无更改"

#: swift/container/updater.py:154
#, python-format
msgid "Container update sweep completed: %.02fs"
msgstr "容器更新扫除完成：%.02fs"

#: swift/container/updater.py:164
msgid "Begin container update single threaded sweep"
msgstr "开始容器更新单线程扫除"

#: swift/container/updater.py:172
#, python-format
msgid ""
"Container update single threaded sweep completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""
"容器更新单线程扫除完成：%(elapsed).02fs, %(success)s 成功, %(fail)s 失败, %(no_change)s 无更改"

#: swift/container/updater.py:224
#, python-format
msgid "Update report sent for %(container)s %(dbfile)s"
msgstr "更新报告发至%(container)s %(dbfile)s"

#: swift/container/updater.py:232
#, python-format
msgid "Update report failed for %(container)s %(dbfile)s"
msgstr "%(container)s %(dbfile)s更新报告失败"

#: swift/container/updater.py:266
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): "
msgstr "错误 账号更新失败%(ip)s:%(port)s/%(device)s (稍后尝试): "

#: swift/obj/auditor.py:61
#, python-format
msgid "Begin object audit \"%s\" mode"
msgstr "开始对象审计 \"%s\" 模式"

#: swift/obj/auditor.py:73
#, python-format
msgid ""
"Since %(start_time)s: Locally: %(passes)d passed audit, %(quars)d "
"quarantined, %(errors)d errors files/sec: %(frate).2f , bytes/sec: "
"%(brate).2f"
msgstr ""
"从 %(start_time)s 起：本地：%(passes)d 个通过的审计，%(quars)d 个被隔离，%(errors)d "
"个错误文件/秒：%(frate).2f，字节/秒：%(brate).2f"

#: swift/obj/auditor.py:90
#, python-format
msgid ""
"Object audit \"%(mode)s\" mode completed: %(elapsed).02fs. Total files/sec: "
"%(frate).2f , Total bytes/sec: %(brate).2f "
msgstr ""
"对象审计\"%(mode)s\"模式完成：%(elapsed).02fs。总计 文件/秒：%(frate).2f ，总计 "
"字节/秒：%(brate).2f "

#: swift/obj/auditor.py:141
#, python-format
msgid "ERROR Object %(obj)s failed audit and will be quarantined: %(err)s"
msgstr "错误 对象%(obj)s 审计失败将被隔离：%(err)s"

#: swift/obj/auditor.py:150
#, python-format
msgid "ERROR Trying to audit %s"
msgstr "错误 尝试开始审计%s"

#: swift/obj/replicator.py:182
msgid "Error hashing suffix"
msgstr "执行Hashing后缀时发生错误"

#: swift/obj/replicator.py:246
#, python-format
msgid "Killing long-running rsync: %s"
msgstr "终止long-running同步: %s"

#: swift/obj/replicator.py:257
#, python-format
msgid "Bad rsync return code: %(args)s -> %(ret)d"
msgstr "不恰当的rsync返回代码：%(args)s -> %(ret)d"

#: swift/obj/replicator.py:261 swift/obj/replicator.py:265
#, python-format
msgid "Successful rsync of %(src)s at %(dst)s (%(time).03f)"
msgstr "成功的rsync %(src)s at %(dst)s (%(time).03f)"

#: swift/obj/replicator.py:350
#, python-format
msgid "Removing partition: %s"
msgstr "移除分区：%s"

#: swift/obj/replicator.py:353
msgid "Error syncing handoff partition"
msgstr "执行同步切换分区时发生错误"

#: swift/obj/replicator.py:383
#, python-format
msgid "%(ip)s/%(device)s responded as unmounted"
msgstr "%(ip)s/%(device)s的回应为未挂载"

#: swift/obj/replicator.py:388
#, python-format
msgid "Invalid response %(resp)s from %(ip)s"
msgstr "无效的回应%(resp)s来自%(ip)s"

#: swift/obj/replicator.py:410
#, python-format
msgid "Error syncing with node: %s"
msgstr "执行同步时节点%s发生错误"

#: swift/obj/replicator.py:414
msgid "Error syncing partition"
msgstr "执行同步分区时发生错误"

#: swift/obj/replicator.py:424
#, python-format
msgid ""
"%(replicated)d/%(total)d (%(percentage).2f%%) partitions replicated in "
"%(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"
msgstr ""
"%(replicated)d/%(total)d (%(percentage).2f%%) 分区被复制 持续时间为 \"\n"
"\"%(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"

#: swift/obj/replicator.py:433
#, python-format
msgid ""
"%(checked)d suffixes checked - %(hashed).2f%% hashed, %(synced).2f%% synced"
msgstr "%(checked)d后缀已被检查 %(hashed).2f%% hashed, %(synced).2f%% synced"

#: swift/obj/replicator.py:439
#, python-format
msgid "Partition times: max %(max).4fs, min %(min).4fs, med %(med).4fs"
msgstr "分区时间: max %(max).4fs, min %(min).4fs, med %(med).4fs"

#: swift/obj/replicator.py:446
#, python-format
msgid "Nothing replicated for %s seconds."
msgstr "%s秒无复制"

#: swift/obj/replicator.py:475
msgid "Lockup detected.. killing live coros."
msgstr "检测到lockup。终止正在执行的coros"

#: swift/obj/replicator.py:530
msgid "Ring change detected. Aborting current replication pass."
msgstr "Ring改变被检测到。退出现有的复制通过"

#: swift/obj/replicator.py:540
msgid "Exception in top-level replication loop"
msgstr "top-level复制圈出现异常"

#: swift/obj/replicator.py:549
msgid "Running object replicator in script mode."
msgstr "在加密模式下执行对象复制"

#: swift/obj/replicator.py:553 swift/obj/replicator.py:565
#, python-format
msgid "Object replication complete. (%.02f minutes)"
msgstr "对象复制完成。(%.02f minutes)"

#: swift/obj/replicator.py:560
msgid "Starting object replication pass."
msgstr "开始通过对象复制"

#: swift/obj/replicator.py:566
#, python-format
msgid "Replication sleeping for %s seconds."
msgstr "复制睡眠 %s 秒。"

#: swift/obj/server.py:313
#, python-format
msgid ""
"ERROR Container update failed (saving for async update later): %(status)d "
"response from %(ip)s:%(port)s/%(dev)s"
msgstr "错误 容器更新失败(正在保存 稍后同步更新)：%(status)d回应来自%(ip)s:%(port)s/%(dev)s"

#: swift/obj/server.py:319
#, python-format
msgid ""
"ERROR container update failed with %(ip)s:%(port)s/%(dev)s (saving for async "
"update later)"
msgstr "错误 容器更新失败%(ip)s:%(port)s/%(dev)s(正在保存 稍后同步更新)"

#: swift/obj/updater.py:65
msgid "Begin object update sweep"
msgstr "开始对象更新扫除"

#: swift/obj/updater.py:89
#, python-format
msgid ""
"Object update sweep of %(device)s completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures"
msgstr "%(device)s对象更新扫除完成：%(elapsed).02fs, %(success)s成功, %(fail)s失败"

#: swift/obj/updater.py:98
#, python-format
msgid "Object update sweep completed: %.02fs"
msgstr "对象更新扫除完成：%.02fs"

#: swift/obj/updater.py:105
msgid "Begin object update single threaded sweep"
msgstr "开始对象更新单线程扫除"

#: swift/obj/updater.py:117
#, python-format
msgid ""
"Object update single threaded sweep completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures"
msgstr "对象更新单线程扫除完成：%(elapsed).02fs,%(success)s 成功, %(fail)s 失败"

#: swift/obj/updater.py:157
#, python-format
msgid "ERROR Pickle problem, quarantining %s"
msgstr "错误 Pickle问题 隔离%s"

#: swift/obj/updater.py:177
#, python-format
msgid "Update sent for %(obj)s %(path)s"
msgstr "为 %(obj)s %(path)s 发送更新"

#: swift/obj/updater.py:182
#, python-format
msgid "Update failed for %(obj)s %(path)s"
msgstr "%(obj)s %(path)s 的更新失败"

#: swift/obj/updater.py:206
#, python-format
msgid "ERROR with remote server %(ip)s:%(port)s/%(device)s"
msgstr "远程服务器发生错误 %(ip)s:%(port)s/%(device)s"

#: swift/proxy/server.py:165 swift/proxy/server.py:629
#: swift/proxy/server.py:696 swift/proxy/server.py:712
#: swift/proxy/server.py:721 swift/proxy/server.py:1004
#: swift/proxy/server.py:1044 swift/proxy/server.py:1089
msgid "Object"
msgstr "对象"

#: swift/proxy/server.py:170
#, python-format
msgid "Could not load object segment %(path)s: %(status)s"
msgstr "无法加载对象segment %(path)s: %(status)s"

#: swift/proxy/server.py:177 swift/proxy/server.py:210
#: swift/proxy/server.py:257
#, python-format
msgid "ERROR: While processing manifest /%(acc)s/%(cont)s/%(obj)s"
msgstr "错误：处理manifest /%(acc)s/%(cont)s/%(obj)s"

#: swift/proxy/server.py:292
#, python-format
msgid "%(msg)s %(ip)s:%(port)s"
msgstr "%(msg)s %(ip)s:%(port)s"

#: swift/proxy/server.py:304
#, python-format
msgid "ERROR with %(type)s server %(ip)s:%(port)s/%(device)s re: %(info)s"
msgstr "%(type)s服务器发生错误 %(ip)s:%(port)s/%(device)s re: %(info)s"

#: swift/proxy/server.py:328
#, python-format
msgid "Node error limited %(ip)s:%(port)s (%(device)s)"
msgstr "节点错误极限 %(ip)s:%(port)s (%(device)s)"

#: swift/proxy/server.py:388 swift/proxy/server.py:1451
#: swift/proxy/server.py:1497 swift/proxy/server.py:1545
#: swift/proxy/server.py:1590
msgid "Account"
msgstr "账号"

#: swift/proxy/server.py:389
#, python-format
msgid "Trying to get account info for %s"
msgstr "尝试为 %s 获取帐户信息"

#: swift/proxy/server.py:466 swift/proxy/server.py:740
#: swift/proxy/server.py:772 swift/proxy/server.py:1214
#: swift/proxy/server.py:1301 swift/proxy/server.py:1356
#: swift/proxy/server.py:1413
msgid "Container"
msgstr "容器"

#: swift/proxy/server.py:467
#, python-format
msgid "Trying to get container info for %s"
msgstr "尝试为 %s 获取容器信息"

#: swift/proxy/server.py:552
#, python-format
msgid "%(type)s returning 503 for %(statuses)s"
msgstr "%(type)s 返回 503 在 %(statuses)s"

#: swift/proxy/server.py:598 swift/proxy/server.py:697
#, python-format
msgid "Trying to %(method)s %(path)s"
msgstr "尝试执行%(method)s %(path)s"

#: swift/proxy/server.py:627
msgid "Client disconnected on read"
msgstr "客户读取时中断"

#: swift/proxy/server.py:630
#, python-format
msgid "Trying to read during GET of %s"
msgstr "在 %s 的GET操作中试图读取"

#: swift/proxy/server.py:653
#, python-format
msgid "ERROR %(status)d %(body)s From %(type)s Server"
msgstr "错误 %(status)d %(body)s 来自 %(type)s 服务器"

#: swift/proxy/server.py:692
#, python-format
msgid "ERROR %(status)d %(body)s From Object Server"
msgstr "错误 %(status)d  来自对象服务器的 %(body)s"

#: swift/proxy/server.py:776 swift/proxy/server.py:783
#, python-format
msgid "Object manifest GET could not continue listing: %s %s"
msgstr "对象manifest GET无法继续进行列表：%s %s"

#: swift/proxy/server.py:905
msgid "Object POST"
msgstr "对象POST"

#: swift/proxy/server.py:1005
#, python-format
msgid "Expect: 100-continue on %s"
msgstr "已知：100-continue on %s"

#: swift/proxy/server.py:1017
#, python-format
msgid "Object PUT returning 503, %(conns)s/%(nodes)s required connections"
msgstr "对象PUT返回503，%(conns)s/%(nodes)s 请求连接"

#: swift/proxy/server.py:1045
#, python-format
msgid "Trying to write to %s"
msgstr "尝试执行书写%s"

#: swift/proxy/server.py:1049
#, python-format
msgid ""
"Object PUT exceptions during send, %(conns)s/%(nodes)s required connections"
msgstr "对象PUT发送时出现异常，%(conns)s/%(nodes)s请求连接"

#: swift/proxy/server.py:1058
#, python-format
msgid "ERROR Client read timeout (%ss)"
msgstr "错误 客户读取超时(%ss)"

#: swift/proxy/server.py:1063
msgid "ERROR Exception causing client disconnect"
msgstr "错误 异常导致客户端中断连接"

#: swift/proxy/server.py:1068
msgid "Client disconnected without sending enough data"
msgstr "客户中断 尚未发送足够"

#: swift/proxy/server.py:1083
#, python-format
msgid "ERROR %(status)d %(body)s From Object Server re: %(path)s"
msgstr "错误 %(status)d %(body)s 来自 对象服务器 re: %(path)s"

#: swift/proxy/server.py:1090
#, python-format
msgid "Trying to get final status of PUT to %s"
msgstr "尝试获取 PUT 至 %s 的最后状态"

#: swift/proxy/server.py:1093
#, python-format
msgid "Object servers returned %s mismatched etags"
msgstr "对象服务器返还%s不匹配etags"

#: swift/proxy/server.py:1101
msgid "Object PUT"
msgstr "对象上传"

#: swift/proxy/server.py:1153
msgid "Object DELETE"
msgstr "对象 DELETE 操作"

#: swift/proxy/server.py:1302 swift/proxy/server.py:1498
#, python-format
msgid "Trying to PUT to %s"
msgstr "试图向 %s 进行PUT操作"

#: swift/proxy/server.py:1314
msgid "Container PUT"
msgstr "容器 PUT 操作"

#: swift/proxy/server.py:1357 swift/proxy/server.py:1546
#, python-format
msgid "Trying to POST %s"
msgstr "试图向 %s 进行 POST 操作"

#: swift/proxy/server.py:1369
msgid "Container POST"
msgstr "容器 POST 操作"

#: swift/proxy/server.py:1414 swift/proxy/server.py:1591
#, python-format
msgid "Trying to DELETE %s"
msgstr "试图 DELETE 操作 %s"

#: swift/proxy/server.py:1426
msgid "Container DELETE"
msgstr "容器 DELETE 操作"

#: swift/proxy/server.py:1433
msgid "Returning 503 because not all container nodes confirmed DELETE"
msgstr "因为并不是所有节点都确定DELETE而返回503"

#: swift/proxy/server.py:1508
msgid "Account PUT"
msgstr "帐户 PUT 操作"

#: swift/proxy/server.py:1556
msgid "Account POST"
msgstr "帐户 POST 操作"

#: swift/proxy/server.py:1601
msgid "Account DELETE"
msgstr "帐户 DELETE 操作"

#: swift/proxy/server.py:1757
msgid "ERROR Unhandled exception in request"
msgstr "错误 未处理的异常发出请求"

#: swift/stats/access_processor.py:63 swift/stats/stats_processor.py:40
#, python-format
msgid "Bad line data: %s"
msgstr "错误行数据：%s"

#: swift/stats/access_processor.py:67
#, python-format
msgid "Bad server name: found \"%(found)s\" expected \"%(expected)s\""
msgstr "错误的服务器名称：找到\"%(found)s\"，预想是\"%(expected)s\""

#: swift/stats/access_processor.py:75
#, python-format
msgid "Invalid path: %(error)s from data: %(log)s"
msgstr "无效的路径：来自数据的错误 %(error)s：%(log)s"

#: swift/stats/access_processor.py:199
#, python-format
msgid ""
"I found a bunch of bad lines in %(name)s (%(bad)d bad, %(total)d total)"
msgstr "在 %(name)s 中找到许多错误行s( %(bad)d 错误, 总共 %(total)d)"

#: swift/stats/account_stats.py:55
msgid "Gathering account stats"
msgstr "收集帐户状态"

#: swift/stats/account_stats.py:59
#, python-format
msgid "Gathering account stats complete (%0.2f minutes)"
msgstr "收集帐户状态完成(%0.2f 分)"

#: swift/stats/account_stats.py:75
#, python-format
msgid "Device %s is not mounted, skipping."
msgstr "设备 %s 没有挂载，跳过。"

#: swift/stats/account_stats.py:81
#, python-format
msgid "Path %s does not exist, skipping."
msgstr "路径 %s 不存在，跳过。"

#: swift/stats/log_processor.py:62
#, python-format
msgid "Loaded plugin \"%s\""
msgstr "加载插件 \"%s\""

#: swift/stats/log_processor.py:79
#, python-format
msgid "Processing %(obj)s with plugin \"%(plugin)s\""
msgstr "用插件 \"%(plugin)s\" 处理 %(obj)s"

#: swift/stats/log_processor.py:179
#, python-format
msgid "Bad compressed data for %s"
msgstr "%s 不恰当的压缩数据"

#: swift/stats/log_processor.py:240
msgid "Beginning log processing"
msgstr "开始日志处理"

#: swift/stats/log_processor.py:278
#, python-format
msgid "found %d processed files"
msgstr "找到 %d 个处理过的文件"

#: swift/stats/log_processor.py:283
#, python-format
msgid "loaded %d files to process"
msgstr "加载 %d 个文件处理"

#: swift/stats/log_processor.py:286 swift/stats/log_processor.py:360
#, python-format
msgid "Log processing done (%0.2f minutes)"
msgstr "日志处理完毕(%0.2f 分)"

#: swift/stats/log_uploader.py:71
msgid "Uploading logs"
msgstr "正在上载日志"

#: swift/stats/log_uploader.py:74
#, python-format
msgid "Uploading logs complete (%0.2f minutes)"
msgstr "上载日志完成(%0.2f 分)"

#: swift/stats/log_uploader.py:129
#, python-format
msgid "Unexpected log: %s"
msgstr "未预想到的日志：%s"

#: swift/stats/log_uploader.py:135
#, python-format
msgid "Skipping log: %(file)s (< %(cutoff)d seconds old)"
msgstr "跳过日志：%(file)s (< %(cutoff)d 秒)"

#: swift/stats/log_uploader.py:142
#, python-format
msgid "Log %s is 0 length, skipping"
msgstr "日志 %s 长度是0，跳过"

#: swift/stats/log_uploader.py:144
#, python-format
msgid "Processing log: %s"
msgstr "处理日志：%s"

#: swift/stats/log_uploader.py:165
#, python-format
msgid "Uploaded log %(file)s to %(target)s"
msgstr "上载 %(file)s 到 %(target)s"

#: swift/stats/log_uploader.py:170
#, python-format
msgid "ERROR: Upload of log %s failed!"
msgstr "错误：日志 %s 上载失败！"
